FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY out/production/kosta308_mini_project ./classes
COPY lib/mysql-connector-j-8.0.33.jar ./lib/mysql-connector-j-8.0.33.jar
COPY lib/lombok.jar ./lib/lombok.jar

CMD ["java", "-Dfile.encoding=UTF-8", \
     "-cp", "./classes:./lib/mysql-connector-j-8.0.33.jar:./lib/lombok.jar", \
     "com.kimdoolim.main.ClientMain"]